# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test123():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):
        # self.driver.quit()
        pass

    def test_ceshiren(self):
        self.driver.get("https://www.baidu.com/")
        text = self.driver.find_element_by_css_selector("#kw")
        ActionChains(self.driver).click(text).send_keys("aaa").key_down(Keys.CONTROL).send_keys("a").perform()

    def test_demo(self):
        pass
